// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonelPuantajUygulamasi.Models;

namespace PersonelPuantajUygulamasi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220818181820_VB-V5")]
    partial class VBV5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PersonelPuantajUygulamasi.Models.Departman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Aciklama")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Ad")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Departmans");
                });

            modelBuilder.Entity("PersonelPuantajUygulamasi.Models.Personel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Ad")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Carsamba")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Cuma")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Cumartesi")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("DepartmanId")
                        .HasColumnType("int");

                    b.Property<string>("Iban")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<decimal>("Maas")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Pazar")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Pazartesi")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Persembe")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Sali")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Soyad")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Telefon")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Personels");
                });

            modelBuilder.Entity("PersonelPuantajUygulamasi.Models.Vardiya", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Ad")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Vardiyas");
                });
#pragma warning restore 612, 618
        }
    }
}
